<!doctype html>
<html lang="[[++context_key]]">
<head>
    [[!isVisited]]

    <base href="[[++site_url]]">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>[[*pagetitle]]</title>
    [[+visit:is=`11`:then=`[[$preloder-style]]`:else=`[[$query-loder-style]]`]]
    [[$preloder-style]]
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700&amp;subset=cyrillic" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:100,300&amp;subset=cyrillic-ext" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/assets.css">

    [[*id:in=`[[babelId?&id=`21`]],[[babelId?&id=`22`]]`:then=`
    <link rel="stylesheet" href="assets/css/architecture.css">
    `]]
    [[*id:is=`[[babelId?&id=`33`]]`:then=`
    <link rel="stylesheet" href="assets/css/building.css">
    `]]
    [[$seo.tpl]]
</head>
<body>
[[$preloder-box-sript]]
<div class="wrapper" style="background-image:url([[#[[*parent]].katalog_image_bg_blur]])">

    <!--left side-->
    [[$left-side]]

    <!--right side-->
    [[$right-side]]

    <!--arrows-->
    [[!prev-next-Page]]

    <!--callback-->
    <a href="" class="callback scale-js-2">
        <div class="callback-wrap">
            <img src="assets/images/callback.png" alt="callback">
        </div>
    </a>


    <!--content-->
    <div class="content">
        <div class="content-wrap">
            <h1>[[#[[*parent]].pagetitle]]</h1>
            <h2>[[*pagetitle]]</h2>
            <div class="content-text">
                <!--more btn-->
                  <div class="scr-more">
                      <img src="assets/images/mouse.png" alt="mouse">
                      <span></span>
                      <span></span>
                  </div>
                [[*id:in=`[[babelId?&ids=`21,22`]]`:then=`[[$architecture]]`]]
                [[*id:is=`[[babelId?&id=`33`]]`:then=`[[$building]]`]]
            </div>
        </div>
    </div>

    [[$slider-galery]]

    [[$foot]]
</div>


<!--scripts-->
<!--libs-->
<script
        src="https://code.jquery.com/jquery-1.12.4.min.js"
        integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
        crossorigin="anonymous"></script>
<script>
    window.onload = function () {
        document.getElementsByClassName('preload-svg')[0].style.zIndex = '-1'
    }
</script>
<script src="assets/js/sub-section.min.js"></script>
[[*id:in=`[[babelId?&ids=`21,22`]]`:then=`
<script src="assets/js/architecture.min.js"></script>
`]]
[[*id:is=`[[babelId?&id=`33`]]`:then=`
<script src="assets/js/building.min.js"></script>
`]]

</body>
</html>
