<!doctype html>
<html lang="[[++cultureKey]]">
<head>
    <meta charset="UTF-8">
    <base href="[[++site_url]]">
    <meta name="robots" content="noindex, nofollow">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>[[*pagetitle:striptags]]</title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400|Roboto:100,300,400,700&amp;subset=cyrillic"
          rel="stylesheet">
    <link rel="stylesheet" href="assets/css/font.css">
    <link rel="stylesheet" href="assets/css/active-house.css">
    <link rel="stylesheet" href="assets/css/queryLoader.css">
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"
        integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <script src="assets/js/lib/queryLoader.js"></script>
    [[$seo.tpl]]
</head>
<body>
<div id="preload">
    <div class="white white-left"></div>
    <div class="white white-right"></div>
    <div class="white-center white-center-left"></div>
    <div class="white-center white-center-right"></div>
    <div class="line-top line"></div>
    <div class="line-bottom line"></div>
    <div class="logo"><img src="assets/images/logo-preload.png" alt="unna logo"></div>
</div>
<div class="wrapper" style="background-image: url([[*katalog_image_bg]])">
    <!--left side-->
    [[$left-side]]
    <!--menu-->
    <header class="header">
        [[Wayfinder?
        &startId=`0`
        &excludeDocs=`[[babelId?&id=`27`]]`
        &level=`2`
        &innerClass=`menu-subitems`
        &outerClass=`menu-bg`
        &innerRowTpl=`innerRowTpl`
        &innerTpl=`m.menu-innerTPL`
        &outerTpl=`m.menu-outerTPL`
        &rowTpl=`m.menu-itemTPL`
        ]]
    </header>
    <!--right side-->
    [[$right-side]]

    <!--callback-->
    <a href="" class="callback scale-js-2">
        <div class="callback-wrap">
            <img src="assets/images/callback.png" alt="callback">
        </div>
    </a>

    <!--content-->
    <div class="content">
        <div class="page-title">
            <h1>[[*pagetitle:limit=`16`]]</h1>
            <h2>[[*longtitle]]</h2>
        </div>
        [[*id:is=`[[++site_start]]`:then=`
        <div class="action">
            <div class="actions">
                <div class="action-head">
                    <div class="action-logo">%</div>
                    <div class="action-title">[[%actions ? &namespace=`unna`]]</div>
                </div>
                [[!getResources?
                &parents=`[[babelId?&id=`36`]]`
                &limit=`1`
                &sortby=`{published:ASC}`
                &tpl=`razdel-action-item-TPL`
                &showHidden=`1`
                ]]

            </div>
            <a href="[[~[[babelId?&id=`36`]]]]" class="all-actions">
                <span>[[%all:ucfirst ? &namespace=`unna`]] [[%actions ? &namespace=`unna`]]</span>
                <svg xmlns="http://www.w3.org/2000/svg" width="17px" viewBox="0 0 72.05 43.92">
                    <defs>
                        <style>.svg-all-actions {
                                fill: none;
                                stroke: #000;
                                stroke-miterlimit: 10;
                                stroke-width: 7px
                            }</style>
                    </defs>
                    <title>arrow</title>
                    <path class="svg-all-actions" d="M69.68 20.68H0M46 .78l24.52 19.95L46 43.19"/>
                </svg>
            </a>
        </div>
        `]]
    </div>


    <!--footer-->
    [[$foot]]
</div>


<!--scripts-->
<script type='text/javascript'>
	QueryLoader.init();
</script>
<script src="assets/js/nav.js"></script>
<script src="assets/js/head-menu.js"></script>
<script src="assets/js/scale.js"></script>
<script src="assets/js/start-anim.js"></script>
</body>
</html>
