<!doctype html>
<html lang="[[++cultureKey]]">
<head>
    [[!isVisited]]
    <meta charset="UTF-8">
    <base href="[[++site_url]]">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>[[*pagetitle:striptags]]</title>
    [[$seo.tpl]]
    [[+visit:is=`1`:then=`[[$preloder-style]]`:else=`[[$query-loder-style]]`]]
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700&amp;subset=cyrillic" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:100,300&amp;subset=cyrillic-ext" rel="stylesheet">

    <link rel="stylesheet" href="assets/css/assets.css">
    <link rel="stylesheet" href="assets/css/active-house.css">
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"
            integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ=" crossorigin="anonymous"></script>
    <script src="assets/js/lib/queryLoader.js"></script>
</head>
<body>
[[+visit:is=`1`:then=`[[$preloder-box-sript]]`:else=`[[$queryLoader]]`]]
<div class="wrapper" style="background-image: url([[*katalog_image_bg]])">
    <!--left side-->
    [[$left-side]]
    <!--menu-->
    <header class="header">
        [[Wayfinder?
        &startId=`0`
        &excludeDocs=`[[babelId?&id=`27`]]`
        &level=`2`
        &innerClass=`menu-subitems`
        &outerClass=`menu-bg`
        &innerRowTpl=`innerRowTpl`
        &innerTpl=`m.menu-innerTPL`
        &outerTpl=`m.menu-outerTPL`
        &rowTpl=`m.menu-itemTPL`
        ]]
    </header>
    <!--right side-->
    [[$right-side]]

    <a href="" class="callback scale-js-2">
        <div class="callback-wrap">
            <img src="assets/images/callback.png" alt="callback">
        </div>
    </a>

    <a href="[[!btnMore]]" class="btn-more scale-js-2">
        <span>Подробнее</span>
        <i class="icon-right-arrow-g"></i>
    </a>
    <!--content-->
    <div class="content">
        <div class="page-title">
            <h1>[[*pagetitle:limit=`16`]]</h1>
            <h2>[[*longtitle]]</h2>
        </div>
        [[*id:is=`[[++site_start]]`:then=`
        <div class="action">
                <a href="[[~[[babelId?&id=`36`]]]]" class="action-left">
                    <div class="action-logo">%</div>
                </a>
                [[!getResources?
                &parents=`[[babelId?&id=`36`]]`
                &limit=`1`
                &sortby=`{publishedon:ASC}`
                &tpl=`razdel-action-item-TPL`
                &showHidden=`1`
                ]]
        </div>
        `]]
    </div>


    <!--footer-->
    [[$foot]]
</div>


<!--scripts-->
[[+visit:ne=`1`:then=`
<script type='text/javascript'>
    QueryLoader.init();
</script>
`]]

<script src="assets/js/section.min.js"></script>

</body>
</html>
