<!doctype html>
<html lang="[[++cultureKey]]">
<head>
    [[!isVisited]]
    <meta charset="UTF-8">
    <base href="[[++site_url]]">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>[[*pagetitle:striptags]]</title>
    [[+visit:is=`1`:then=`[[*id:ne=`[[babelId?&id=`6`]]`:then=`[[$preloder-style]]`]]`:else=`[[$query-loder-style]]`]]
    <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,700&amp;subset=cyrillic" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:100,300&amp;subset=cyrillic-ext" rel="stylesheet">

    <link rel="stylesheet" href="assets/css/jquery.mCustomScrollbar.min.css"/>
    <link rel="stylesheet" href="assets/css/assets.css">


    [[*id:is=`[[babelId?&id=`9`]]`:then=`
    <link rel="stylesheet" href="assets/css/advantages.css">
    `]]
    [[*id:is=`[[babelId?&id=`8`]]`:then=`
    <link rel="stylesheet" href="assets/css/location.css">
    `]]
    [[*id:is=`[[babelId?&id=`6`]]`:then=`
    <link rel="stylesheet" href="assets/css/contacts.css">
    `]]
    [[*id:is=`[[babelId?&id=`36`]]`:then=`
    <link rel="stylesheet" href="assets/css/actions.css">
    `]]
    [[*id:is=`[[babelId?&id=`12`]]`:then=`
    <link rel="stylesheet" href="assets/css/news.css">
    `]]

    [[*id:in=`[[babelId?&ids=`7,24`]]`:then=`
    <link rel="stylesheet" href="assets/css/complex.css">
    `]]
    [[*id:is=`[[babelId?&id=`30`]]`:then=`
    <link rel="stylesheet" href="assets/css/developer.css">
    `]]
    [[*id:is=`[[babelId?&id=`5`]]`:then=`
    <link rel="stylesheet" href="assets/css/documentation.css">
    `]]
    [[*id:in=`[[babelId?&ids=`29,10,14`]]`:then=`
    <link rel="stylesheet" href="assets/css/masplan.css">
    `]]

    [[$seo.tpl]]

    [[*id:in=`[[babelId?&ids=`6,8`]]`:then=`
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCy85hurU5pPvup9lMcp2H6y5G3LrrsEXE" async
            defer></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    `:else=`
    <script src="https://code.jquery.com/jquery-1.12.4.min.js"
            integrity="sha256-ZosEbRLbNQzLpnKIkEdrPv7lOy9C27hHQ+Xp8a4MxAQ="
            crossorigin="anonymous">
    </script>
    `]]
    <script src="assets/js/lib/queryLoader.js"></script>
</head>
<body>

[[+visit:is=`1`:then=`[[*id:ne=`[[babelId?&id=`6`]]`:then=`[[$preloder-box-sript]]`]]`:else=`[[$queryLoader]]`]]


<!---->
<div class="wrapper" [[*katalog_image_bg:!empty=`style="background-image: url([[*katalog_image_bg]])"`]]>
[[*id:is=`[[babelId?&id=`12`]]`:then=`
<div class="to-blur" style="background-image: url('assets/images/news_bg.jpg')"></div>
`]]
<!--left side-->
[[$left-side]]

<!--right side-->
[[$right-side]]

<!--arrows-->
[[!prev-next-Page]]

<!--callback-->
<a href="" class="callback scale-js-2">
    <div class="callback-wrap">
        <img src="assets/images/callback.png" alt="callback">
    </div>
</a>


[[*id:is=`[[babelId?&id=`6`]]`:then=`[[$contact_chank]]`:else=`
<!--content-->
<div class="content">
    <div class="content-wrap">
        <h1>[[#[[*parent]].pagetitle]]</h1>
        [[*template:ne=`29`:then=`<h2>[[*pagetitle]]</h2>`:else=`<h1>[[*pagetitle]]</h1>`]]
        <div class="content-text[[*id:is=`[[babelId?&id=`8`]]`:then=` scale-js-1`]]">
            [[*id:is=`[[babelId?&id=`9`]]`:then=`[[$advantages]]`]]
            [[*id:is=`[[babelId?&id=`5`]]`:then=`[[$documents]]`]]
            [[*id:is=`[[babelId?&id=`8`]]`:then=`[[$location-content]]`]]
            [[*id:in=`[[babelId?&ids=`36,12`]]`:then=`[[$stocks]]`]]
            [[*id:is=`[[babelId?&id=`29`]]`:then=`<p><img src="[[*genplan]]" alt="Unna genplan"></p>`]]
            [[*id:is=`[[babelId?&id=`30`]]`:then=`[[$developer_chank]]`]]

            <p>[[*content]]</p>
        </div>
    </div>
</div>
`]]
[[*id:is=`[[babelId?&id=`9`]]`:then=`[[$advantages-slider]]`]]
[[*id:is=`[[babelId?&id=`8`]]`:then=`[[$location-map-info]]`]]

[[$foot]]
</div>

<!--scripts-->
[[+visit:ne=`1`:then=`
<script type='text/javascript'>
    QueryLoader.init();
</script>
`]]
[[*id:in=`[[babelId?&id=`6,8`]]`:then=`
<script src="http://code.jquery.com/jquery-migrate-3.0.0.js"></script>
`]]

[[*id:is=`[[babelId?&id=`8`]]`:then=`
<script src="assets/js/location.js"></script>
`]]
[[*id:is=`[[babelId?&id=`6`]]`:then=`
<script src="assets/js/contacts.js"></script>
`]]

<script src="assets/js/jquery.mCustomScrollbar.concat.min.js"></script>
[[*id:ne=`12`:and:ne=`6`:then=`
<script src="assets/js/sub-section.min.js"></script>
`:else=`
<script src="assets/js/section.min.js"></script>
`]]
<!---->


[[*id:in=`[[babelId?&ids=`7,29,10,30,24,14`]]`:then=`
<script src="assets/js/complex.min.js"></script>
`]]

[[*id:is=`[[babelId?&id=`9`]]`:then=`
<script src="assets/js/advantages.min.js"></script>
`]]
[[*id:is=`[[babelId?&id=`36`]]`:then=`
<script src="assets/js/actions.min.js"></script>
`]]
[[*id:is=`[[babelId?&id=`12`]]`:then=`
<script src="assets/js/news.min.js"></script>

`]]

</body>
</html>
