[[$mobile-head]]

<section class="section1">
    <div class="container">
        <h1>[[*pagetitle]]</h1>
    </div>
</section>
<section class="section2">
    <div class="container">
        <p>[[%gallery-text?&namespace=`unna`]]</p>
        <ul>
            <li id="[[#[[babelId?&id=`21`]].alias]]">
                <a href="#[[~[[*id]]]][[#[[babelId?&id=`21`]].alias]]"><i class="icon-architecture"></i><span>[[#[[babelId?&id=`21`]].pagetitle]]</span></a>
                <div class="hidden">
                    <div class="slider">
                        [[!getImageList?
                        &tvname=`migx_galery-architec`
                        &docid=`[[babelId?&id=`21`]]`
                        &tpl=`@CODE: <img src="[[+image]]" alt="[[+title]]">`
                        ]]
                    </div>
                </div>
            </li>
            <li id="[[#[[babelId?&id=`22`]].alias]]">
                <a href="#[[~[[*id]]]][[#[[babelId?&id=`22`]].alias]]"><i class="icon-plans"></i><span>[[#[[babelId?&id=`22`]].pagetitle]]</span></a>
                <div class="hidden">
                    <div class="slider">
                        [[!getImageList?
                        &tvname=`migx_galery-architec`
                        &docid=`[[babelId?&id=`22`]]`
                        &tpl=`@CODE: <img src="[[+image]]" alt="[[+title]]">`
                        ]]
                    </div>
                </div>
            </li>
            <li><a href="#[[~[[*id]]]][[#[[babelId?&id=`23`]].alias]]"><i><img src="assets/images/webcam.svg"
                                                                   alt="webcam"></i><span>[[#[[babelId?&id=`23`]].pagetitle]]</span></a>
            </li>
            <li id="[[#[[babelId?&id=`33`]].alias]]">
                <a href="#[[~[[*id]]]][[#[[babelId?&id=`33`]].alias]]"><i class="icon-crane"></i><span>[[#[[babelId?&id=`33`]].pagetitle]]</span></a>
                <div class="hidden">
                    <div class="gallery-history">
                        <!-- year -->
                        [[!getImageList?
                        &docid=`[[babelId?&id=`33`]]`
                        &tvname=`migx_Gallery`
                        &tpl=`mobile-building-yaer-TPL`
                        ]]
                    </div>
                </div>
            </li>
        </ul>
    </div>
</section>
<section class="section3">
    <div class="container">
        <div class="links">
            <a href="[[#[[babelId?&id=`27`]].buklet_PDF]]">
                <img src="assets/images/booklet-icon.png" alt="download booklet">
                <span>[[%download:ucfirst? &namespace=`unna`]] [[%buklet? &namespace=`unna`]]</span>
            </a>
            <a href="[[#[[babelId?&id=`27`]].presentation]]">
                <i class="icon-video-player"></i>
                <span>[[%look:ucfirst? &namespace=`unna`]] [[%video? &namespace=`unna`]][[%presentation? &namespace=`unna`]]</span>
            </a>
        </div>
    </div>
</section>
[[$mobile-foot]]
