[[$mobile-head]]
<section class="section1">
    <div class="container">
        <h1>[[*pagetitle]]</h1>
    </div>
</section>
<section class="section2">
    <div class="container">
        <p>Вы можете наблюдать за ходом строительства он-лайн или просмотреть фотоотчет.</p>
        <ul>
            <li><a href="#[[#[[babelId?&id=`21`]].alias]]"><i class="icon-architecture"></i><span>Архитектура</span></a>
            </li>
            <li><a href="#[[#[[babelId?&id=`22`]].alias]]"><i class="icon-plans"></i><span>Интерьеры</span></a></li>
            <li><a href="#[[#[[babelId?&id=`23`]].alias]]"><i><img src="assets/images/webcam.svg"
                                                                   alt="webcam"></i><span>Прямой эфир</span></a></li>
            <li><a href="#[[#[[babelId?&id=`33`]].alias]]"><i class="icon-crane"></i><span>Ход строительства</span></a>
            </li>
        </ul>
    </div>
</section>
<section class="section3" id="[[#[[babelId?&id=`21`]].alias]]">
    <div class="container">
        <h2>[[#[[babelId?&id=`21`]].pagetitle]]</h2>
        <div class="slider">
            [[!getImageList?
            &tvname=`migx_galery-architec`
            &docid=`[[babelId?&id=`21`]]`
            &tpl=`@CODE: <img src="[[+image]]" alt="[[+title]]">`
            ]]
        </div>
    </div>
</section>
<section class="section4" id="[[#[[babelId?&id=`33`]].alias]]">
    <div class="container">
        <h2>[[#[[babelId?&id=`33`]].pagetitle]]</h2>
        <div class="gallery-history">
            <!-- year -->
            <div class="year">
                <span>2017</span>
                <div class="hidden">
                    <!-- season -->
                    <div class="season">
                        <span>Зима 2016 - 2017</span>
                        <div class="hidden">
                            [[!getImageList?

                            &tpl=`mobile-building-month-TPL`

                            ]]
                            <!-- month -->
                            <div class="month">
                                <span>Январь 2017</span>
                                <div class="hidden">
                                    <div class="slider">
                                        <img src="assets/images/mobile-gallery3.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3a.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3b.jpg" alt="gallery">
                                    </div>
                                </div>
                            </div>
                            <!-- month -->
                            <div class="month">
                                <span>Февраль 2017</span>
                                <div class="hidden">
                                    <div class="slider">
                                        <img src="assets/images/mobile-gallery3b.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3a.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3.jpg" alt="gallery">
                                    </div>
                                </div>
                            </div>
                            <!-- month -->
                        </div>
                    </div>
                    <!-- season -->
                    <div class="season">
                        <span>Осень 2016</span>
                        <div class="hidden">
                            <div class="month">
                                <span>Сентябрь 2016</span>
                                <div class="hidden">
                                    <div class="slider">
                                        <img src="assets/images/mobile-gallery3a.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3b.jpg" alt="gallery">
                                    </div>
                                </div>
                            </div>
                            <!-- month -->
                            <div class="month">
                                <span>Октябрь 2016</span>
                                <div class="hidden">
                                    <div class="slider">
                                        <img src="assets/images/mobile-gallery3.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3a.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3b.jpg" alt="gallery">
                                    </div>
                                </div>
                            </div>
                            <!-- month -->
                            <div class="month">
                                <span>Ноябрь 2016</span>
                                <div class="hidden">
                                    <div class="slider">
                                        <img src="assets/images/mobile-gallery3b.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3a.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3.jpg" alt="gallery">
                                    </div>
                                </div>
                            </div>
                            <!-- month -->
                        </div>
                    </div>
                    <!-- season -->
                    <div class="season">
                        <span>Лето 2016</span>
                        <div class="hidden">
                            <div class="month">
                                <span>Июнь 2016</span>
                                <div class="hidden">
                                    <div class="slider">
                                        <img src="assets/images/mobile-gallery3a.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3b.jpg" alt="gallery">
                                    </div>
                                </div>
                            </div>
                            <!-- month -->
                            <div class="month">
                                <span>Июль 2016</span>
                                <div class="hidden">
                                    <div class="slider">
                                        <img src="assets/images/mobile-gallery3.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3a.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3b.jpg" alt="gallery">
                                    </div>
                                </div>
                            </div>
                            <!-- month -->
                            <div class="month">
                                <span>Авнуст 2016</span>
                                <div class="hidden">
                                    <div class="slider">
                                        <img src="assets/images/mobile-gallery3b.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3a.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3.jpg" alt="gallery">
                                    </div>
                                </div>
                            </div>
                            <!-- month -->
                        </div>
                    </div>
                    <!-- season -->
                </div>
            </div>
            <!-- year -->
            <div class="year">
                <span>2016</span>
                <div class="hidden">
                    <!-- season -->
                    <div class="season">
                        <span>Зима 2016 - 2017</span>
                        <div class="hidden">
                            <div class="month">
                                <span>Декабрь 2016</span>
                                <div class="hidden">
                                    <div class="slider">
                                        <img src="assets/images/mobile-gallery3a.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3b.jpg" alt="gallery">
                                    </div>
                                </div>
                            </div>
                            <!-- month -->
                            <div class="month">
                                <span>Январь 2017</span>
                                <div class="hidden">
                                    <div class="slider">
                                        <img src="assets/images/mobile-gallery3.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3a.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3b.jpg" alt="gallery">
                                    </div>
                                </div>
                            </div>
                            <!-- month -->
                            <div class="month">
                                <span>Февраль 2017</span>
                                <div class="hidden">
                                    <div class="slider">
                                        <img src="assets/images/mobile-gallery3b.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3a.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3.jpg" alt="gallery">
                                    </div>
                                </div>
                            </div>
                            <!-- month -->
                        </div>
                    </div>
                    <!-- season -->
                    <div class="season">
                        <span>Осень 2016</span>
                        <div class="hidden">
                            <div class="month">
                                <span>Сентябрь 2016</span>
                                <div class="hidden">
                                    <div class="slider">
                                        <img src="assets/images/mobile-gallery3a.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3b.jpg" alt="gallery">
                                    </div>
                                </div>
                            </div>
                            <!-- month -->
                            <div class="month">
                                <span>Октябрь 2016</span>
                                <div class="hidden">
                                    <div class="slider">
                                        <img src="assets/images/mobile-gallery3.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3a.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3b.jpg" alt="gallery">
                                    </div>
                                </div>
                            </div>
                            <!-- month -->
                            <div class="month">
                                <span>Ноябрь 2016</span>
                                <div class="hidden">
                                    <div class="slider">
                                        <img src="assets/images/mobile-gallery3b.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3a.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3.jpg" alt="gallery">
                                    </div>
                                </div>
                            </div>
                            <!-- month -->
                        </div>
                    </div>
                    <!-- season -->
                    <div class="season">
                        <span>Лето 2016</span>
                        <div class="hidden">
                            <div class="month">
                                <span>Июнь 2016</span>
                                <div class="hidden">
                                    <div class="slider">
                                        <img src="assets/images/mobile-gallery3a.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3b.jpg" alt="gallery">
                                    </div>
                                </div>
                            </div>
                            <!-- month -->
                            <div class="month">
                                <span>Июль 2016</span>
                                <div class="hidden">
                                    <div class="slider">
                                        <img src="assets/images/mobile-gallery3.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3a.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3b.jpg" alt="gallery">
                                    </div>
                                </div>
                            </div>
                            <!-- month -->
                            <div class="month">
                                <span>Авнуст 2016</span>
                                <div class="hidden">
                                    <div class="slider">
                                        <img src="assets/images/mobile-gallery3b.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3a.jpg" alt="gallery">
                                        <img src="assets/images/mobile-gallery3.jpg" alt="gallery">
                                    </div>
                                </div>
                            </div>
                            <!-- month -->
                        </div>
                    </div>
                    <!-- season -->
                </div>
            </div>
            <!-- year -->
        </div>
        <div class="links">
            <a href="#">
                <img src="assets/images/booklet-icon.png" alt="download booklet">
                <span>скачать буклет</span>
            </a>
            <a href="#">
                <i class="icon-video-player"></i>
                <span>смотреть видеопрезентацию</span>
            </a>
        </div>
    </div>
</section>
[[$mobile-foot]]