[[$mobile-head]]
<section class="section1">
    <div class="container">
        <h1>[[#[[babelId?&id=`1`]].pagetitle]]</h1>

        <img src="assets/images/logo.png" class="logo" alt="Unna logo">
        <div class="live-cam">
            <a class="link-delay" href="live-cam-site.html"></a>
            <svg xmlns="http://www.w3.org/2000/svg" width="25px" height="27px" viewBox="0 0 22.67 23.24">
                <defs>
                    <style>
                        .webcam-1 {
                            fill: none;
                            stroke: #fff;
                            stroke-miterlimit: 10;
                        }
                    </style>
                </defs>
                <title>web-cam</title>
                <g>
                    <path class="webcam-1"
                          d="M15.6,18.87c-.09.23-1.08.44-1.37.64-2.41.21-2.83.58-7.08-.59-3.91.3-6.65,1-6.65,1.83,0,1.1,4.85,2,10.83,2s10.83-.89,10.83-2C22.17,19.87,19.88,19.13,15.6,18.87Z"></path>
                    <g class="web-cam-cent">
                        <ellipse class="webcam-1" cx="11.24" cy="10.12" rx="10.54" ry="9.62"></ellipse>
                        <ellipse class="webcam-1" cx="11.24" cy="10.12" rx="5.55" ry="5.06"></ellipse>
                        <ellipse class="webcam-1" cx="11.24" cy="10.22" rx="3.9" ry="3.56"></ellipse>
                    </g>
                </g>
            </svg>
            <span>[[%web.link ? &namespace=`unna`]]</span>
        </div>
    </div>
</section>
<section class="section2 about" id="[[#[[babelId?&id=`7`]].alias]]">
    <div class="container">
        <h2>[[#[[babelId?&id=`7`]].pagetitle:striptags]]</h2>
        <p>[[#[[babelId?&id=`7`]].content]]</p>
        <!--        <img src="assets/images/mobile-main2.jpg" alt="Unna full house">-->
        <div class="links">
            <a href="#">
                <img src="assets/images/booklet-icon.png" alt="download booklet">
                <span>[[%download:ucfirst? &namespace=`unna`]] [[%buklet? &namespace=`unna`]]</span>
            </a>
            <a href="#">
                <i class="icon-video-player"></i>
                <span>[[%look:ucfirst? &namespace=`unna`]] [[%video? &namespace=`unna`]][[%presentation? &namespace=`unna`]]</span>
            </a>
        </div>
        <div class="mobile-scroll"><img src="assets/images/scroll-icon.png" alt="scroll icon"></div>
    </div>
</section>
<section class="section3 location" id="[[#[[babelId?&id=`8`]].alias]]">
    <div class="container">
        <h2>[[#[[babelId?&id=`8`]].pagetitle:striptags]]</h2>
        <div class="content-text scale-js-1">
            <div class="location-hide active">
                <i class="icon-eye-see"></i>
                <span>[[%location.all? &namespace=`unna`]]</span>
            </div>
            <div class="location-filter">
                <div class="location-type" data-group="sport">
                    <i class="icon-dumbbell"></i>
                </div>
                <div class="location-type" data-group="kids">
                    <i class="icon-teddy-bear"></i>
                </div>
                <div class="location-type" data-group="study">
                    <i class="icon-mortarboard"></i>
                </div>
                <div class="location-type" data-group="medicine">
                    <i class="icon-first-aid-kit"></i>
                </div>
                <div class="location-type" data-group="parks">
                    <i class="icon-tree"></i>
                </div>
                <div class="location-type" data-group="shopping">
                    <i class="icon-shopping-cart"></i>
                </div>
            </div>
        </div>
        <div id="locationMap"></div>
        <div id="locationInfo">
            [[$location-map-info]]
        </div>
    </div>
</section>
<section class="section4 genplan" id="[[#[[babelId?&id=`29`]].alias]]">
    <div class="container">
        <h2>[[#[[babelId?&id=`29`]].pagetitle:striptags]]</h2>
        <img src="[[#[[babelId?&id=`29`]].genplan]]" alt="Unna генплан">
    </div>
</section>
<section class="section5 advantages" id="[[#[[babelId?&id=`9`]].alias]]">
    <div class="container">
        <h2>[[#[[babelId?&id=`9`]].pagetitle:striptags]]</h2>
        <div class="slider">
            [[!getImageList?
            &tvname=`migx-advantages`
            &docid=`[[babelId?&id=`9`]]`
            &tpl=`advantage-mobile-slider-item`]]
        </div>
    </div>
</section>
<section class="section6 haracteristics" id="[[#[[babelId?&id=`10`]].alias]]">
    <div class="container">
        <h2>[[#[[babelId?&id=`10`]].pagetitle:striptags]]</h2>
        <ul>
            [[!getImageList? &docid=`[[babelId?&id=`10`]]` &tvname=`migx-tex-haracteristics` &tpl=`@CODE:
            <li>[[+haracter]]</li>
            `]]
        </ul>
    </div>
</section>
<section class="section7 developer" id="[[#[[babelId?&id=`30`]].alias]]">
    <div class="container">
        <h2>[[#[[babelId?&id=`30`]].pagetitle:striptags]]</h2>
        <p>[[#[[babelId?&id=`30`]].content]]</p>
    </div>
</section>
<section class="section9 partners">
    <div class="container">
        <div class="pertners">
            [[!getImageList?
            &docid=`[[babelId?&id=`30`]]`
            &tvname=`migx-partners-catalog`
            &tpl=`partner-catalog-mobile-item`
            ]]
        </div>
    </div>
</section>
<section class="section8 perspective">
    <div class="container">
        <h2>[[#[[babelId?&id=`30`]].project_title]]</h2>
        [[!getImageList?
        &docid=`[[babelId?&id=`30`]]`
        &tvname=`migx-project-colection`
        &tpl=`@CODE: <a href="[[+link]]"><img src="[[+image]]" alt="[[+title]]"></a>
        <h3>[[+title]]</h3>`
        ]]
        <p>[[#[[babelId?&id=`30`]].content:striptags:limit=`250`]]</p>
    </div>
</section>
<section class="section10 documentation" id="[[#[[babelId?&id=`5`]].alias]]">
    <div class="container">
        <h2>[[#[[babelId?&id=`5`]].pagetitle:striptags]]</h2>
        <ul>
            [[!getImageList?
            &tvname=`migx_documents`
            &docid=`[[babelId?&id=`5`]]`
            &tpl=`@CODE:
            <li>[[+title]] <a href="[[+file]]"><i
                            class="icon-pdf-file-outlined-interface-symbol"></i></a></li>
            `]]
        </ul>
    </div>
</section>
[[$mobile-foot]]
