[[$mobile-head]]
<section class="section1">
    <div class="container">
        <h1>[[*pagetitle]]</h1>
    </div>
</section>
<section class="section2">
    <div class="container">
        <div class="news" data-all="[[+total]][[!getResources?&parents=`[[*id]]`&tpl=`@INLINE`&showHidden=`1`]]">
            [[!more_News_Ajax]]
        </div>
        <div class="news-more">
            <a href="facebook.com" target="_blank" rel="nofollow">[[%facebook? &namespace=`unna`]]</a>
            <a id="loadMoreNews" class="green-button" href="#">[[%larger? &namespace=`unna`]] [[%nesw?
                &namespace=`unna`]] <i class="icon-right-arrow"></i></a>
        </div>
    </div>
</section>

[[$mobile-foot]]