[[$mobile-head]]
<section class="section1" style="background: url('assets/images/aparts-mobile.jpg') no-repeat center center">
    <div class="container">
        <h1>[[*pagetitle]]</h1>
    </div>
</section>

<div class="container">
    <div clas="content-wrap">
        <div class="aparts">
            <div class="filters filter_aparts">
                [[*id:is=`[[babelId?&id=`31`]]`:then=`[[!setFilter]]`]]
                <h3 class="title">
                    [[%apart_filter? &namespace=`unna`]]
                </h3>
                <form>
                    <div class="filter_block filter">
                        <div class="body">
                            <ul>
                                <li>
                                    <label class="filter_row">
                                        <input type="radio" name="rooms" value="1"/>
                                        <div>
                                            <span class="num">1</span>
                                            <span>[[%room? &namespace=`unna`]]</span>
                                        </div>
                                    </label>
                                </li>
                                <li>
                                    <label class="filter_row">
                                        <input type="radio" name="rooms" value="2"/>
                                        <div>
                                            <span class="num">2</span>
                                            <span>[[%room? &namespace=`unna`]]</span>
                                        </div>
                                    </label>
                                </li>
                                <li>
                                    <label class="filter_row">
                                        <input type="radio" name="rooms" value="3"/>
                                        <div>
                                            <span class="num">3</span>
                                            <span>[[%room? &namespace=`unna`]]</span>
                                        </div>
                                    </label>
                                </li>
                                <li>
                                    <label class="filter_row">
                                        <input type="radio" name="levels" value="2"/>
                                        <div>
                                            <span class="num">2х</span>
                                            <span>[[%levels? &namespace=`unna`]]</span>
                                        </div>
                                    </label>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="filter_block filter">
                        <div class="body">
                            <ul>
                                <li>
                                    <div class="range-slider sizes disabled" >
                                        <div class="ui-slider-range-left"></div>
                                        <div class="ui-slider-range"></div>
                                        <div class="ui-slider-range-right"></div>
                                        <div class="left-limit-value" data-value="[[+area-min]]"></div>
                                        <div class="right-limit-value" data-value="[[+area-max]]"></div>
                                        <a href="#" class="ui-slider-handle left-handle origin"
                                           data-value="[[+area-min]]"></a>
                                        <a href="#" class="ui-slider-handle right-handle origin"
                                           data-value="[[+area-max]]"></a>
                                        <input type="hidden" name="full-area-from" value=""/>
                                        <input type="hidden" name="full-area-to" value=""/>
                                    </div>
                                    <div class="filter-title">
                                        [[%area? &namespace=`unna`]], [[%metr? &namespace=`unna`]]<sup>2</sup>
                                    </div>
                                </li>
                                <li>
                                    <div class="range-slider prices disabled" >
                                        <div class="ui-slider-range-left"></div>
                                        <div class="ui-slider-range"></div>
                                        <div class="ui-slider-range-right"></div>
                                        <div class="left-limit-value" data-value="[[+price-min]]"></div>
                                        <div class="right-limit-value" data-value="[[+price-max]]"></div>
                                        <a href="#" class="ui-slider-handle left-handle"
                                           data-value="[[+price-min]]"></a>
                                        <a href="#" class="ui-slider-handle right-handle"
                                           data-value="[[+price-max]]"></a>
                                        <input type="hidden" name="full-price-from" value=""/>
                                        <input type="hidden" name="full-price-to" value=""/>
                                    </div>
                                    <div class="filter-title">
                                        [[%cena? &namespace=`unna`]], [[%thousand? &namespace=`unna`]] [[%uah? &namespace=`unna`]]
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </form>
            </div>
            <div class="aparts_list">
            </div>
        </div>
        <div class="storerooms">
            <h3>[[#[[babelId?&id=`24`]].pagetitle]]</h3>
            [[#[[babelId?&id=`24`]].content:ellipsis=`300`]]
            <a href="#" class="show_more">
                [[%learn? &namespace=`unna`]] [[%more? &namespace=`unna`]]
            </a>
        </div>
        <div class="premises">
            <div class="filters filter_premises">
                <h3 class="title">[[%premises_filter?&namespace=`unna`]]</h3>
                <form>
                    <div class="filter_block filter">
                        <div class="body">
                            <ul>
                                <li>
                                    <label class="filter_row">
                                        <input type="radio" name="floor" data-floor="1"/>
                                        <div>
                                            <span class="num letter">Ц</span>
                                            <span>[[#[[babelId?&id=`3`]].prem-cokol-title]]</span>
                                        </div>
                                    </label>
                                </li>
                                <li>
                                    <label class="filter_row">
                                        <input type="radio" name="floor" data-floor="2"/>
                                        <div>
                                            <span class="num">1</span>
                                            <span>[[#[[babelId?&id=`3`]].prem-1-title]]</span>
                                        </div>
                                    </label>
                                </li>
                            </ul>
                        </div>
                    </div>
                </form>
            </div>
            <div class="floors">
                <div class="floor">
                    <img src="assets/images/premises/podval-black.png"/>
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1635 928.67">
                        <defs>
                            <style>.cls-1, .cls-15, .cls-3 {
                                    fill: #dbabab;
                                }</style>
                        </defs>
                        <g id="Слой_2" data-name="Слой 2">
                            <g id="Слой_37" data-name="Слой 37">
                                <polygon class="cls-1" data-link="1"
                                         points="1538.33 895.67 1635 895.67 1634.67 641.67 1367 534.33 1367 803.33 1537.67 803.33 1538.33 895.67"/>
                                <g id="Слой_38" data-name="Слой 38" class="cls-2">
                                    <polygon class="cls-3" data-link="2"
                                             points="1241.67 482.33 1241.67 619.33 1369.67 619.33 1369.67 534.33 1241.67 482.33"/>
                                </g>
                                <g id="Слой_39" data-name="Слой 39" class="cls-4">
                                    <polygon class="cls-3" data-link="3"
                                             points="1241.67 619.67 1241.67 483.33 980.67 378.33 980.67 550.67 1093.67 550.67 1093.67 618.67 1241.67 619.67"/>
                                </g>
                                <g id="Слой_40" data-name="Слой 40" class="cls-2">
                                    <rect class="cls-3" data-link="4" x="1039.67" y="548.67" width="54" height="67"/>
                                </g>
                                <g id="Слой_41" data-name="Слой 41" class="cls-5">
                                    <rect class="cls-3" data-link="5" x="979.67" y="548.67" width="60" height="67"/>
                                </g>
                                <g id="Слой_42" data-name="Слой 42" class="cls-6">
                                    <polygon class="cls-3" data-link="6"
                                             points="899.67 618.67 899.67 412.67 979.67 412.67 979.67 376.67 723.67 274.67 723.67 619.67 899.67 618.67"/>
                                </g>
                                <g id="Слой_43" data-name="Слой 43" class="cls-7">
                                    <polygon class="cls-3" data-link="7"
                                             points="722.83 274.83 723.67 619.67 547.67 619.67 548.33 204.33 722.83 274.83"/>
                                </g>
                                <g id="Слой_44" data-name="Слой 44" class="cls-8">
                                    <polygon class="cls-3" data-link="8"
                                             points="547.67 620.33 547.67 537.67 464.67 537.67 462.17 620 547.67 620.33"/>
                                </g>
                                <g id="Слой_45" data-name="Слой 45" class="cls-9">
                                    <polygon class="cls-3" data-link="9"
                                             points="327.67 583.67 407.67 583.67 407.67 510.67 326.67 510.67 327.67 583.67"/>
                                </g>
                                <g id="Слой_46" data-name="Слой 46" class="cls-10">
                                    <rect class="cls-3" data-link="10" x="326.67" y="442.67" width="81" height="68"/>
                                </g>
                                <g id="Слой_47" data-name="Слой 47" class="cls-8">
                                    <polygon class="cls-3" data-link="11"
                                             points="326.67 440.33 464.67 440.33 464.67 375.33 549.17 377.83 548.67 204.33 273.67 93.33 274 246.17 326.17 246.17 326.67 440.33"/>
                                </g>
                                <g id="Слой_48" data-name="Слой 48" class="cls-11">
                                    <polygon class="cls-3" data-link="12"
                                             points="273.5 245.42 273.5 93 41.67 0 41.67 67.33 0 67.33 0 245.67 273.5 245.42"/>
                                </g>
                                <g id="Слой_49" data-name="Слой 49" class="cls-12">
                                    <polygon class="cls-3" data-link="13"
                                             points="0 332.33 81.67 331.67 81.67 310.67 280.33 310.67 280.33 524.67 1 524.33 0 332.33"/>
                                </g>
                                <g id="Слой_50" data-name="Слой 50" class="cls-13">
                                    <rect class="cls-3" data-link="14" x="41.67" y="524.33" width="239.33"
                                          height="95.33"/>
                                </g>
                                <g id="Слой_51" data-name="Слой 51" class="cls-14">
                                    <polygon class="cls-15" data-link="15"
                                             points="275.67 697.67 42.67 697.67 42.67 890.67 430.67 890.67 430.67 712.67 274.67 712.67 275.67 697.67"/>
                                </g>
                                <g id="Слой_52" data-name="Слой 52" class="cls-16">
                                    <rect class="cls-3" data-link="16" x="326.67" y="665.67" width="104" height="55"/>
                                </g>
                                <g id="Слой_53" data-name="Слой 53" class="cls-17">
                                    <path class="cls-3" data-link="17"
                                          d="M427.67,894.67v-220h291V895S439,894.67,427.67,894.67Z"/>
                                </g>
                                <g id="Слой_54" data-name="Слой 54" class="cls-18">
                                    <path class="cls-3" data-link="18"
                                          d="M718.67,894.67l-3.33-219h313l3.33,219H999.33c-.66,0,.33,34,.33,34H934s.06-32.83-.5-32.83C846.11,895.83,730.8,894.67,718.67,894.67Z"/>
                                </g>
                                <g id="Слой_55" data-name="Слой 55" class="cls-19">
                                    <polygon class="cls-3" data-link="19"
                                             points="1031.67 675.67 1031.67 895.33 1091 895.33 1091 928.33 1158 928.33 1158 895.33 1203.67 895.33 1203.67 674.67 1031.67 675.67"/>
                                </g>
                                <g id="Слой_56" data-name="Слой 56" class="cls-20">
                                    <polygon class="cls-3" data-link="20"
                                             points="1203.67 674.33 1203.67 895 1257.33 895 1257 928 1317.67 928 1317.67 674.33 1203.67 674.33"/>
                                    <path class="cls-3" d="M1256.33,896"/>
                                </g>
                            </g>
                        </g>
                    </svg>
                    <div class="links">
                        [[getResources?
                        &parents=`[[babelId?&id=`3`]]`
                        &sortby=`{menuindex:ASC}`
                        &limit=`0`
                        &includeTVs=`1`
                        &tvFilters=`level==Ц`
                        &tpl=`@INLINE <a href="#" data-link="[[+idx]]" data-resource="[[+id]]"></a>`
                        ]]
                    </div>
                </div>
                <div class="floor">
                    <img src="assets/images/premises/perviy-black.png"/>
                    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1641.64 885.79">
                        <defs>
                            <style>.cls-2 {
                                    fill: #f2c0c0;
                                }

                                .cls-10, .cls-4 {
                                    fill: #dbabab;
                                }</style>
                        </defs>
                        <g id="Слой_2" data-name="Слой 2">
                            <g id="Слой_2-2" data-name="Слой 2" class="cls-1">
                                <path class="cls-2" data-link="1"
                                      d="M495.24,874.48c0-7,.5-24,.5-24h6v-179h-222v-22h-232l1,201.5s324,.93,420.5.93C473.74,869,478.74,872.5,495.24,874.48Z"/>
                            </g>
                            <g id="Слой_3" data-name="Слой 3" class="cls-3">
                                <polygon class="cls-4" data-link="2"
                                         points="501.74 850.5 501.74 671.5 438.74 671.5 438.74 620.5 738.74 620.5 741.74 849.5 501.74 850.5"/>
                            </g>
                            <g id="Слой_4" data-name="Слой 4" class="cls-5">
                                <polygon class="cls-4" data-link="3"
                                         points="134.74 572.5 284.74 572.5 284.74 267.5 97.74 267.5 97.74 292.5 0 292.5 0 480.5 134.74 480.5 134.74 572.5"/>
                            </g>
                            <g id="Слой_5" data-name="Слой 5" class="cls-6">
                                <path class="cls-4" data-link="4"
                                      d="M0,292.5V17.5H97.74c.5-9.5,10.5-17,23.5-17.5V17.5h85.5l101,43v138h-24l-1,68L98,267.25l-.25,25.25Z"/>
                            </g>
                            <g id="Слой_6" data-name="Слой 6" class="cls-7">
                                <polygon class="cls-4" data-link="5"
                                         points="307.74 60.5 490.74 133.5 490.74 282.5 471.74 282.5 471.74 399.5 334.74 399.5 334.74 380.5 283.74 380.5 283.74 192.5 306.74 192.5 307.74 60.5"/>
                            </g>
                            <g id="Слой_7" data-name="Слой 7" class="cls-8">
                                <polygon class="cls-4" data-link="6"
                                         points="555.74 488.5 554.74 273.5 621.74 273.5 621.74 185.5 742.74 235 742.74 486.5 555.74 488.5"/>
                                <polygon class="cls-4" data-link="7"
                                         points="899.24 853 900.24 620.5 1038.74 620.5 1037.74 853 1005.24 853 1005.24 882.5 940.24 882.5 940.74 853 899.24 853"/>
                            </g>
                            <g id="Слой_8" data-name="Слой 8" class="cls-9">
                                <polygon class="cls-4" data-link="8"
                                         points="1038.74 852.33 1038.74 621.33 1106.74 621.33 1106.74 445.83 1049.74 445.83 1049.74 424.83 982.24 424.83 982.74 331.5 1256.24 441.5 1257.74 633.83 1210.74 633.83 1210.74 852.33 1164.24 852.33 1164.74 883.83 1100.24 883.83 1099.74 852.33 1038.74 852.33"/>
                            </g>
                            <g id="Слой_10" data-name="Слой 10" class="cls-8">
                                <polygon class="cls-4" data-link="9"
                                         points="1210.74 852.5 1210.74 626.5 1254.74 626.5 1254.74 555.5 1376.74 555.5 1376.74 885.79 1262.74 885.12 1262.74 852.81 1210.74 852.5"/>
                            </g>
                            <g id="Слой_32" data-name="Слой 32">
                                <polygon class="cls-10" data-link="10"
                                         points="1546.14 850.99 1641.64 850.99 1641.64 595.5 1381.64 491 1381.64 766.49 1545.24 766.49 1546.14 850.99"/>
                            </g>
                        </g>
                    </svg>
                    <div class="links">
                        [[getResources?
                        &parents=`[[babelId?&id=`3`]]`
                        &sortby=`{menuindex:ASC}`
                        &limit=`0`
                        &includeTVs=`1`
                        &tvFilters=`level==1`
                        &tpl=`@INLINE <a href="#" data-link="[[+idx]]" data-resource="[[+id]]"></a>`
                        ]]
                    </div>
                </div>
            </div>
            <div class="premises_list">
            </div>
        </div>
        <!--<div class="terms">
            <h3>Условия покупки</h3>
            <div class="text">
                Жилой комплекс на Лиговском проспекте - знаковый проект как для компании, так и для Санкт-Петербурга.
                Территория комплекса входит в так называемый "серый пояс", редевелопмент которого сегодня в числе
                приоритетных градостроительных задач. Жилой квартал станет первым проектом в рамках реновации бывшей
                промышленной своеобразной точкой отсчета нового облика района. Проект представляет собой современный
                15-секционный 11-этажный жилой дом, построенный по технологии монолита с вентилируемым фасадом. Дом
                будет оснащен
            </div>
        </div>-->
    </div>
</div>
[[$mobile-foot]]