<!--<h3>[[*partner_title]]</h3>-->
[[!getImageList?
&docid=`[[*id]]`
&tvname=`migx-partners-catalog`
&tpl=`partner-catalog-item`
]]
<h3>[[*project_title]]</h3>
<p>[[!getImageList?
    &docid=`[[*id]]`
    &tvname=`migx-project-colection`
    &tpl=`project-item`
    ]]
</p>